# =====================================================================
# For a full TOML configuration guide, check the Flower docs:
# https://flower.ai/docs/framework/how-to-configure-pyproject-toml.html
# =====================================================================

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fl-cityscapes-bisenetv2"
version = "1.0.0"
description = ""
license = "Apache-2.0"
# Dependencies for your Flower App
dependencies = [
    "flwr[simulation]>=1.23.0",
    "flwr-datasets[vision]>=0.5.0",
    "torch==2.7.1",
    "torchvision==0.22.1",
    "tqdm",
    "opencv-python",
    "tabulate"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "moustafa"

# Point to your ServerApp and ClientApp objects
[tool.flwr.app.components]
serverapp = "fl_cityscapes_bisenetv2.server_app:app"
clientapp = "fl_cityscapes_bisenetv2.client_app:app"

# Custom config values accessible via `context.run_config`
[tool.flwr.app.config]
# Server-side FL config
num-server-rounds = 3
fraction-train = 0.5
fraction-evaluate = 0.0
server-device = "cpu"

# Client-side FL config
local-epochs = 1
batch_size = 4

# Dataset Paths
im_root = "./datasets/cityscapes"
client_data_partition = "./datasets/cityscapes/city_partitions.json"

# Model Configs
num_classes = 19

lr = 5e-3
weight_decay = 5e-4

num_aux_heads = 4

scales = "[0.25, 2.0]"
cropsize = "[512, 1024]"

# Results path
respth = "./final_model.pt"

# Default federation to use when running the app
[tool.flwr.federations]
default = "local-simulation-single-gpu"

# Local simulation federation with 18 virtual SuperNodes
[tool.flwr.federations.local-simulation-single-gpu]
options.num-supernodes = 18
options.backend.client-resources.num-cpus = 2
options.backend.client-resources.num-gpus = 1.0

# Remote federation example for use with SuperLink
[tool.flwr.federations.remote-federation]
address = "<SUPERLINK-ADDRESS>:<PORT>"
insecure = true  # Remove this line to enable TLS
# root-certificates = "<PATH/TO/ca.crt>"  # For TLS setup
