# =====================================================================
# For a full TOML configuration guide, check the Flower docs:
# https://flower.ai/docs/framework/how-to-configure-pyproject-toml.html
# =====================================================================

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fl-cityscapes-bisenetv2"
version = "1.0.0"
description = ""
license = "Apache-2.0"
# Dependencies for your Flower App
dependencies = [
    "flwr[simulation]>=1.23.0",
    "flwr-datasets[vision]>=0.5.0",
    "torch==2.7.1",
    "torchvision==0.22.1",
    "tqdm",
    "opencv-python",
    "tabulate"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "moustafa"

# Point to your ServerApp and ClientApp objects
[tool.flwr.app.components]
serverapp = "fl_cityscapes_bisenetv2.server_app:app"
clientapp = "fl_cityscapes_bisenetv2.client_app:app"

# Custom config values accessible via `context.run_config`
[tool.flwr.app.config]
# Server-side FL config
strategy_name = "FedAvg" # Options: FedAvg, FedAvgM, FedProx
num-server-rounds = 50
fraction-train = 0.5
fraction-evaluate = 0.0
server-device = "cuda"

# Server Loading Config
resume = false
pretrained_path = "./res/latest_model.pt"
rounds_trained = 0 # IMPORTANT Need Update on Resume

# Server evaluation config
eval-batch-size = 1
eval-interval = 3

# Client-side FL config
client-device = "cuda"

local-epochs = 1
batch_size = 4

# Dataset Paths
im_root = "./datasets/cityscapes"
client_data_partition = "./datasets/cityscapes/city_partitions.json"
server_data_partition = "./datasets/cityscapes/val.txt"

# Model Configs
num_classes = 19

lr = 5e-3 # IMPORTANT Need Update on Resume

weight_decay = 5e-4

num_aux_heads = 4

scales = "[0.25, 2.0]"
cropsize = "[512, 1024]"

# Results path
save_latest = "./res/latest_model.pt"
save_best = "./res/best_model.pt"

best_miou = 0.0 # IMPORTANT Need Update on Resume
best_metric = "./res/best_metric.json"
latest_metric = "./res/latest_metric.json"

# Default federation to use when running the app
[tool.flwr.federations]
default = "local-simulation-single-gpu"

# Local simulation federation with 18 virtual SuperNodes
[tool.flwr.federations.local-simulation-single-gpu]
options.num-supernodes = 18
options.backend.client-resources.num-cpus = 2
options.backend.client-resources.num-gpus = 1.0

# Remote federation example for use with SuperLink
[tool.flwr.federations.remote-federation]
address = "<SUPERLINK-ADDRESS>:<PORT>"
insecure = true  # Remove this line to enable TLS
# root-certificates = "<PATH/TO/ca.crt>"  # For TLS setup
